indent = 2
margin = 110
always_for_in = true
remove_extra_newlines = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
whitespace_in_kwargs = false
separate_kwargs_with_semicolon = true
pipe_to_function_call = false
always_use_return = false
annotate_untyped_fields_with_any = true
trailing_comma = true
surround_whereop_typeparameters = true
align_assignment=true