indent = 2
margin = 92
whitespace_ops_in_indices = true
remove_extra_newlines = true
whitespace_in_kwargs = true
always_for_in = true
whitespace_typedefs = true
remove_extra_newlines = true
pipe_to_function_call = false
always_use_return = false
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = true
trailing_comma = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
