name: CD
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Releasee ${{ matrix.arch }}
    strategy:
      matrix:
        version: ["lts"] # julia version
        arch:
          - x64
          - arm64
        include:
          - arch: x64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Print system architecture
        run: uname -m

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}

      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Build and package app tarball
        run: |
          julia build.jl -t auto -O3 --startup-file=no --heap-size-hint=6G
          mv target stonks
          tar -czf stonks_${{ matrix.arch }}.tar.gz stonks > errors.txt
          cat ./errors.txt 

      - name: Upload app tarball
        uses: actions/upload-artifact@v4
        with:
          name: stonks_${{ matrix.arch }}.tar.gz
          path: stonks_${{ matrix.arch }}.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: stonks_${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.STONKS_GITHUB_TOKEN }}
