name: CI
on:
  push:
    branches: [main, develop]
    paths-ignore:
      - README.md
      - Dockerfile
      - .JuliaFormatter.toml
      - .gitignore
      - .pre-commit-config.yaml
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["lts"]
        os: [ubuntu-latest]
        arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      # - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
